import { Inter } from "next/font/google";
import "./globals.css";
import localFont from '@next/font/local'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const vazir = localFont({
  src: [
    {
      path: '../../public/Fonts/Vazir.ttf',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../../public/Fonts/Vazir.ttf',
      weight: '400',
      style: 'normal',
    },
  ],

});
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={vazir.className}>{children}</body>
    </html>
  );
}
